######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 9 15:10:53 2014
######################################################################

CONFIG += x86 
TEMPLATE = app
TARGET = accesModClient
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += accesmod.cpp
QT += webkit widgets
