######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 12 13:03:04 2014
######################################################################

TEMPLATE = app
TARGET = accessmodClient 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += accesmod.cpp
QT += webkitwidgets webkit widgets

