######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 9 15:10:53 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += accesmod.cpp
QT += webkit widgets
